"""
Read-Only SQL Sanitizer
───────────────────────
A regex-based shield that sits between the LLM-generated SQL and the
DuckDB execution engine.

Purpose:
  Gemini writes SQL → this module inspects it → only SELECT passes.
  Any destructive statement (DROP, DELETE, ALTER, INSERT, UPDATE,
  CREATE, TRUNCATE, ATTACH, COPY, EXPORT, IMPORT, LOAD, INSTALL)
  is immediately rejected with a SecurityError before it ever
  touches the database.

Design Philosophy:
  Defence-in-depth. Even though we instruct the LLM to only produce
  SELECT queries, a jailbreak or prompt-injection could slip through.
  This module is the last firewall.
"""

from __future__ import annotations

import re
import logging

logger = logging.getLogger(__name__)


# ── Exceptions ───────────────────────────────────────────────────────────

class SQLInjectionBlocked(Exception):
    """Raised when a destructive SQL statement is detected."""

    def __init__(self, statement: str, matched_keyword: str):
        self.statement = statement
        self.matched_keyword = matched_keyword
        super().__init__(
            f"Blocked destructive SQL: '{matched_keyword.upper()}' "
            f"detected in query."
        )


# ── Blocked Patterns ────────────────────────────────────────────────────

# Each pattern is anchored to word boundaries to avoid false positives
# (e.g., a column named "updated_at" should NOT trigger "UPDATE").
_DESTRUCTIVE_KEYWORDS: list[str] = [
    r"\bDROP\b",
    r"\bDELETE\b",
    r"\bALTER\b",
    r"\bINSERT\b",
    r"\bUPDATE\b",
    r"\bCREATE\b",
    r"\bTRUNCATE\b",
    r"\bATTACH\b",
    r"\bDETACH\b",
    r"\bCOPY\b",
    r"\bEXPORT\b",
    r"\bIMPORT\b",
    r"\bLOAD\b",
    r"\bINSTALL\b",
    r"\bPRAGMA\b",
    r"\bGRANT\b",
    r"\bREVOKE\b",
    r"\bEXECUTE\b",
    r"\bCALL\b",
    r"\bSET\b",
]

_DESTRUCTIVE_PATTERN = re.compile(
    "|".join(_DESTRUCTIVE_KEYWORDS),
    re.IGNORECASE,
)

# Additional shield: block multiple statements (semicolons followed
# by another keyword) to prevent piggy-backed injections like:
#   SELECT 1; DROP TABLE users;
_MULTI_STATEMENT_PATTERN = re.compile(
    r";\s*\w",
    re.IGNORECASE,
)


# ── Public API ───────────────────────────────────────────────────────────

def sanitize_sql(raw_sql: str) -> str:
    """
    Validates that `raw_sql` is a safe, read-only SELECT query.

    Returns the cleaned SQL string if safe.
    Raises SQLInjectionBlocked if any destructive pattern is found.

    Args:
        raw_sql: The SQL string generated by the LLM.

    Returns:
        The same SQL string, stripped of leading/trailing whitespace.

    Raises:
        SQLInjectionBlocked: If a destructive keyword or multi-statement
                             pattern is detected.

    Examples:
        >>> sanitize_sql("SELECT AVG(salary) FROM employees")
        'SELECT AVG(salary) FROM employees'

        >>> sanitize_sql("DROP TABLE employees")
        Traceback (most recent call last):
        ...
        SQLInjectionBlocked: Blocked destructive SQL: 'DROP' detected in query.

        >>> sanitize_sql("SELECT 1; DROP TABLE users")
        Traceback (most recent call last):
        ...
        SQLInjectionBlocked: Blocked destructive SQL: 'MULTI_STATEMENT' ...
    """
    cleaned = raw_sql.strip()

    if not cleaned:
        raise SQLInjectionBlocked(cleaned, "EMPTY_QUERY")

    # ── Check 1: Multi-statement injection ───────────────────────────
    if _MULTI_STATEMENT_PATTERN.search(cleaned):
        logger.warning(
            "[SQL Sanitizer] BLOCKED multi-statement injection: %s",
            cleaned[:100],
        )
        raise SQLInjectionBlocked(cleaned, "MULTI_STATEMENT")

    # ── Check 2: Destructive keyword scan ────────────────────────────
    match = _DESTRUCTIVE_PATTERN.search(cleaned)
    if match:
        keyword = match.group(0)
        logger.warning(
            "[SQL Sanitizer] BLOCKED keyword '%s' in: %s",
            keyword,
            cleaned[:100],
        )
        raise SQLInjectionBlocked(cleaned, keyword)

    # ── Check 3: Must start with SELECT or WITH (CTEs) ───────────────
    normalized = cleaned.lstrip().upper()
    if not normalized.startswith(("SELECT", "WITH")):
        logger.warning(
            "[SQL Sanitizer] BLOCKED non-SELECT query: %s",
            cleaned[:100],
        )
        raise SQLInjectionBlocked(cleaned, "NON_SELECT")

    logger.debug("[SQL Sanitizer] PASSED: %s", cleaned[:80])
    return cleaned
